- plugins/confluence.go
Implement mechanism to get previous versions content
> Refactor Confluence Plugin

- .gitignore
- lib/http.go
- plugins/confluence.go
- feat(confluence): filter spaces
- fix(confluence): use username and token
- chore: move httpRequest to lib
> Use Auth and filter spaces

- .github/workflows/pr-validation.yml
- .github/workflows/release.yml
- Dockerfile
- Makefile
Fix #34
- create docker image
- create makefile
- validate docker on pr-validation
- upload tar image to Github release
- run Kics on pr-validation
- fix Kics issues
> infra: create docker image

- reporting/report.go
> fix: remove secret location from report

- .github/workflows/release.yml
- split into 3 depends jobs
- publish to Dockerhub
For #77 (not closing until testing it)
> cd: release docker image to dockerhub on manual version

- plugins/confluence.go
- plugins/discord.go
- plugins/paligo.go
- plugins/plugins.go
- plugins/repository.go
- plugins/slack.go
All IDs are now usable for the user
> refactor: remove unused Source field

- cmd/main.go
- plugins/filesystem.go
- plugins/git.go
- plugins/repository.go
- refactor: repository plugin initialization
- change repository to filesystem
- repository plugin - support scanning historical git commits
Fixes #66
> feat: support scanning historical git commits

- .github/workflows/gosec.yml
Added [gosec](https://github.com/securego/gosec)
> ci: add gosec check

- plugins/filesystem.go
> fix: crash when using filesystem plugin

- cmd/main.go
- plugins/discord.go
- chore: validate format on preRun
- fix: discord finished without secret scanning
> fix: discord finished without secret scanning

- README.md
- cmd/main.go
- plugins/filesystem.go
- secrets/secrets.go
- add ignore flag
- rename filesystem `--ignore` to `--ignore-pattern`
- ignore secrets by ID
Close #35
> feat: add option to ignore specific result by ID

- .github/workflows/release.yml
- .gitignore
> feat: cross-compilation

- README.md
- plugins/confluence.go
> fix: scan public Confluence without credentials

- .github/workflows/gosec.yml
- .github/workflows/pr-validation.yml
- .github/workflows/validate-readme.yml
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
> ci: enable merge queue

- README.md
- plugins/confluence.go
Closes #138 
-Change to README file.
-Change to confluence file in the DefineCommand function.
-
> feat: confluence url is mandatory arg 

- .ci/check_new_rules.go
- cmd/main.go
- secrets/rules/rule.go
- secrets/rules/rules.go
- secrets/rules/rules_test.go
- secrets/secrets.go
- secrets/secrets_test.go
- rename loadAllRules to loadDefaultRules
- chore: move rules filtering to rules.go
> chore: move rules filtering to rules.go

- .github/workflows/security.yml
- CONTRIBUTING.md
- README.md
- reporting/report.go
- tests/cli.go
- tests/cli_test.go
- tests/lint.go
- tests/lint_test.go
- test: prevent log.Fatal and fmt.Print
- fix: using fmt.Print for report
> test: add lint and e2e tests

- .github/workflows/release.yml
I missed few actions on the previous commit #213
> ci: upgrade more github actions

- docs/list-of-rules.md
- engine/rules/authenticated_url.go
- engine/rules/rules.go
> fix: unstabe rules and false positives in auth URL

- .github/workflows/release.yml
Fix golang lint issue with semantic version
**Checklist**
> feat: update release.yml

- lib/reporting/sarif.go
Added the property bag to Sarif Results ("properties"), in accordance with SARIF guidelines.
Added validationStatus to properties of each result in SARIF, in line with what already happens in JSON.
**Checklist**
> feat: ast 40209 added validation status to sarif report

- .github/workflows/release.yml
Updated golangci-lint version (which prevented the release workflow from running successfully).
**Checklist**
> feat: update golangci-lint version

- .github/workflows/ast-scan.yml
Adding SCA validation thresholds to CxOne scan
> ci: add SCA thresholds

- .github/CODEOWNERS
> ci: create codeowners file

- .github/workflows/security.yml
Added skip for Trivy's updates
> feat: skip trivy update

- go.mod
Still need to update the dockerfile image later
> chore: update go to 1.24.6
